### ISSUE TITLE
ToDo 

### ISSUE THREAD

**Issue by omearamike** [omearamike/etsyfavscript#2]
- [ ] Make Json to control all the settings.
- [ ] Limit size of the log file.
- [ ] Limit the size of the log file.
- [ ] Still needs to be fully tested.
- [ ] Test methods need to be contained in different file.
- [ ] Improve run time output.
- [ ] Update readme to Include what files will be created when the Script Runs
